### ISSUE TITLE
No Demandware Project Wizard

### ISSUE THREAD

**Issue by ranveer5289** [nek4life/intellij-demandware#15]
I installed the latest Webstorm & installed the plugin from Repository.

Plugin got installed successfully. After installation I cannot see Demandware in Create New Project Wizard.

Webstorm Details:

```
WebStorm 2016.2.3
Build #WS-162.1812.21, built on September 4, 2016
Licensed to WebStorm Evaluator
Expiration date: October 22, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

I have JDK8/JRE8 installed on my OSX machine.

I the main menu I can see only option for `Clean Cartridge`

[Screenshot](http://i.imgur.com/mB397vY.png)

Also, can you please add some screenshots  of the plugin usage. :)

**Comment by nek4life** [comment]
Hi Ranveer,

I've gotten quite a few reports that the plugin does not work with Webstorm. I think the problem is that the custom module I wrote is not a web module in intellij plugin speak so there is no way to get to the project settings. You would need to use Intellij Idea to use the plugin.

I will be honest I haven't had time to work on the project in quite some time. I would love some help with it! :D 

I will try to add some screenshots.

Thanks,
Charlie

**Comment by ranveer5289** [comment]
Hi @nek4life 

Thanks. I installed Intellij idea and after installing plugin I can see DWRE in project wizard.

I can clean the cartridges and upload them to server.

But how do I upload an individual file. When I save the file it doesn't upload any changes to server neither I see any progress bar.

I see messages like below when I clean the cartridge

```
[04:05:07] Cleaned https://dev29-world01-xxxx.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/version1
```

**Comment by nek4life** [comment]
You need to mark each cartridge as a source root by right clicking on the cartridge in the project window. This will tell the plugin which cartridge to upload. Hope that helps!

**Comment by ranveer5289** [comment]
I already did this and `clean cartridge` commands works successfully but I cannot upload individual files.

![alt text](http://i.imgur.com/fVI2tZp.png)

**Comment by nek4life** [comment]
Did you check auto upload in the configuration settings?

**Comment by nek4life** [comment]
![screen shot 2016-09-22 at 3 07 51 pm](https://cloud.githubusercontent.com/assets/16930/18762339/5aff638a-80d6-11e6-8ffe-d9391edf5d15.png)

**Comment by ranveer5289** [comment]
I have that field checked

![alt text](http://i.imgur.com/ndvNTlf.png)

**Comment by ranveer5289** [comment]
Got it working. 

Created a new workspace and it worked perfectly fine 👍 

Thanks for all the help

**Comment by nek4life** [comment]
Great glad you got it working!
